package com.voidcitymc.blocks;

public enum Biome {
    OCEAN,
    BEACH,
    SCORCHED,
    TUNDRA,
    BARE,
    TEMPERATE_DESERT,
    SHRUBLAND,
    GRASSLAND,
    TEMPERATE_DECIDUOUS_FOREST,
    TEMPERATE_RAIN_FOREST,
    SUBTROPICAL_DESERT,
    TROPICAL_SEASONAL_FOREST,
    TROPICAL_RAIN_FOREST,
    SNOW,
    TAIGA
}
